import SpeechEmotion from "@/components/speechemotion";
import { Layouts } from "react-grid-layout";

export const layouts: Record<string, Layouts> = {
  all: {
    lg: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 2 },
      { i: "speechEmotion", x: 0, y: 2, w: 1, h: 2 },
      { i: "cardStack", x: 0, y: 3, w: 2, h: 2 },
      { i: "goldPrice", x: 0, y: 4, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 2 },
      { i: "driverDrowsiness", x: 1, y: 2, w: 2, h: 2 },
      { i: "tinySwords", x: 2, y: 0, w: 1, h: 2 },
      { i: "hemo", x: 3, y: 2, w: 2, h: 2 },
      { i: "cyberSleuth", x: 2, y: 1, w: 1, h: 2 },
      { i: "musicGenre", x: 3, y: 0, w: 1, h: 4 },
      { i: "about", x: 3, y: 1, w: 1, h: 2 },
    ],
    md: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 2 },
      { i: "speechEmotion", x: 0, y: 2, w: 1, h: 2 },
      { i: "cardStack", x: 0, y: 3, w: 2, h: 2 },
      { i: "goldPrice", x: 0, y: 4, w: 2, h: 2 },
      { i: "themeSwitch", x: 1, y: 1, w: 1, h: 2 },
      { i: "driverDrowsiness", x: 1, y: 2, w: 2, h: 2 },
      { i: "tinySwords", x: 2, y: 0, w: 1, h: 2 },
      { i: "hemo", x: 3, y: 2, w: 2, h: 2 },
      { i: "cyberSleuth", x: 2, y: 1, w: 1, h: 2 },
      { i: "musicGenre", x: 3, y: 0, w: 1, h: 4 },
      { i: "about", x: 3, y: 1, w: 1, h: 2 },
    ],
    sm: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "tinySwords", x: 0, y: 2, w: 2, h: 1 },
      { i: "speechEmotion", x: 0, y: 3, w: 2, h: 2 },
      { i: "themeSwitch", x: 0, y: 4, w: 1, h: 1 },
      { i: "about", x: 1, y: 4, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 5, w: 1, h: 1 },
      { i: "goldPrice", x: 0, y: 6, w: 2, h: 1 },
      { i: "driverDrowsiness", x: 0, y: 7, w: 2, h: 1 },
      { i: "cardStack", x: 0, y: 8, w: 2, h: 2 },
      { i: "hemo", x: 0, y: 10, w: 2, h: 1 },
      { i: "cyberSleuth", x: 0, y: 11, w: 2, h: 1 },
      { i: "musicGenre", x: 0, y: 12, w: 2, h: 2 },

    ],
    xs: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "tinySwords", x: 0, y: 2, w: 2, h: 1 },
      { i: "speechEmotion", x: 0, y: 3, w: 2, h: 2 },
      { i: "themeSwitch", x: 0, y: 4, w: 1, h: 1 },
      { i: "about", x: 1, y: 4, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 5, w: 1, h: 1 },
      { i: "goldPrice", x: 0, y: 6, w: 2, h: 1 },
      { i: "driverDrowsiness", x: 0, y: 7, w: 2, h: 1 },
      { i: "cardStack", x: 0, y: 8, w: 2, h: 2 },
      { i: "hemo", x: 0, y: 10, w: 2, h: 1 },
      { i: "cyberSleuth", x: 0, y: 11, w: 2, h: 1 },
      { i: "musicGenre", x: 0, y: 12, w: 2, h: 2 },

    ],
    xxs: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "tinySwords", x: 0, y: 2, w: 2, h: 1 },
      { i: "speechEmotion", x: 0, y: 3, w: 2, h: 2 },
      { i: "themeSwitch", x: 0, y: 4, w: 1, h: 1 },
      { i: "about", x: 1, y: 4, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 5, w: 1, h: 1 },
      { i: "goldPrice", x: 0, y: 6, w: 2, h: 1 },
      { i: "driverDrowsiness", x: 0, y: 7, w: 2, h: 1 },
      { i: "cardStack", x: 0, y: 8, w: 2, h: 2 },
      { i: "hemo", x: 0, y: 10, w: 2, h: 1 },
      { i: "cyberSleuth", x: 0, y: 11, w: 2, h: 1 },
      { i: "musicGenre", x: 0, y: 12, w: 2, h: 2 },
    ],
  },

  about: {
    lg: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "cardStack", x: 2, y: 0, w: 2, h: 2 },
      { i: "iconCloud", x: 0, y: 1, w: 1, h: 2 },
      { i: "about", x: 1, y: 1, w: 1, h: 2 },
      { i: "themeSwitch", x: 2, y: 1, w: 1, h: 2 },
      { i: "tinySwords", x: 3, y: 1, w: 1, h: 2 },
      { i: "speechEmotion", x: 0, y: 2, w: 1, h: 2 },
      { i: "goldPrice", x: 0, y: 3, w: 2, h: 2 },
      { i: "driverDrowsiness", x: 1, y: 2, w: 2, h: 2 },
      { i: "hemo", x: 0, y: 4, w: 2, h: 2 },
      { i: "cyberSleuth", x: 3, y: 2, w: 1, h: 2 },
      { i: "musicGenre", x: 2, y: 3, w: 1, h: 4 },
    ],
    md: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "cardStack", x: 3, y: 0, w: 2, h: 2 },
      { i: "iconCloud", x: 1, y: 1, w: 1, h: 2 },
      { i: "miniModel", x: 0, y: 1, w: 1, h: 2 },
      { i: "themeSwitch", x: 1, y: 2, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 1, w: 1, h: 2 },
      { i: "animatedEmoji", x: 2, y: 2, w: 1, h: 2 },
      { i: "webAgent", x: 3, y: 0, w: 1, h: 4 },
      { i: "chatBot", x: 0, y: 2, w: 2, h: 2 },
      { i: "actions", x: 3, y: 2, w: 2, h: 2 },
      { i: "paper", x: 0, y: 3, w: 1, h: 2 },
    ],
    sm: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 0, y: 2, w: 1, h: 1 },
      { i: "about", x: 1, y: 2, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 3, w: 1, h: 1 },
      { i: "cardStack", x: 0, y: 4, w: 2, h: 2 },

      { i: "tinySwords", x: 0, y: 5, w: 2, h: 1 },
      { i: "speechEmotion", x: 0, y: 6, w: 2, h: 2 },
      { i: "goldPrice", x: 0, y: 8, w: 2, h: 1 },
      { i: "driverDrowsiness", x: 0, y: 9, w: 2, h: 1 },
      { i: "hemo", x: 0, y: 10, w: 2, h: 1 },
      { i: "cyberSleuth", x: 0, y: 11, w: 2, h: 1 },
      { i: "musicGenre", x: 0, y: 12, w: 2, h: 2 },
    ],
    xs: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 0, y: 2, w: 1, h: 1 },
      { i: "about", x: 1, y: 2, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 3, w: 1, h: 1 },
      { i: "cardStack", x: 0, y: 4, w: 2, h: 2 },

      { i: "tinySwords", x: 0, y: 5, w: 2, h: 1 },
      { i: "speechEmotion", x: 0, y: 6, w: 2, h: 2 },
      { i: "goldPrice", x: 0, y: 8, w: 2, h: 1 },
      { i: "driverDrowsiness", x: 0, y: 9, w: 2, h: 1 },
      { i: "hemo", x: 0, y: 10, w: 2, h: 1 },
      { i: "cyberSleuth", x: 0, y: 11, w: 2, h: 1 },
      { i: "musicGenre", x: 0, y: 12, w: 2, h: 2 },
    ],
    xxs: [
      { i: "avatar", x: 0, y: 0, w: 2, h: 2 },
      { i: "themeSwitch", x: 0, y: 2, w: 1, h: 1 },
      { i: "about", x: 1, y: 2, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 3, w: 1, h: 1 },
      { i: "cardStack", x: 0, y: 4, w: 2, h: 2 },

      { i: "tinySwords", x: 0, y: 5, w: 2, h: 1 },
      { i: "speechEmotion", x: 0, y: 6, w: 2, h: 2 },
      { i: "goldPrice", x: 0, y: 8, w: 2, h: 1 },
      { i: "driverDrowsiness", x: 0, y: 9, w: 2, h: 1 },
      { i: "hemo", x: 0, y: 10, w: 2, h: 1 },
      { i: "cyberSleuth", x: 0, y: 11, w: 2, h: 1 },
      { i: "musicGenre", x: 0, y: 12, w: 2, h: 2 },
    ],
  },

  projects: {
    lg: [
      { i: "speechEmotion", x: 0, y: 0, w: 1, h: 2 },
      { i: "driverDrowsiness", x: 1, y: 0, w: 2, h: 2 },
      { i: "tinySwords", x: 3, y: 0, w: 1, h: 2 },
      { i: "goldPrice", x: 0, y: 1, w: 2, h: 2 },
      { i: "musicGenre", x: 2, y: 1, w: 1, h: 4 },
      { i: "cyberSleuth", x: 3, y: 1, w: 1, h: 2 },
      { i: "hemo", x: 0, y: 2, w: 2, h: 2 },

      { i: "avatar", x: 0, y: 3, w: 2, h: 2 },
      { i: "cardStack", x: 3, y: 3, w: 2, h: 2 },
      { i: "iconCloud", x: 0, y: 4, w: 1, h: 2 },
      { i: "about", x: 1, y: 4, w: 1, h: 2 },
      { i: "themeSwitch", x: 3, y: 2, w: 1, h: 2 },
    ],
    md: [
      { i: "chatBot", x: 1, y: 0, w: 2, h: 2 },
      { i: "animatedEmoji", x: 3, y: 0, w: 1, h: 2 },
      { i: "webAgent", x: 0, y: 0, w: 1, h: 4 },
      { i: "paper", x: 1, y: 1, w: 1, h: 2 },
      { i: "actions", x: 2, y: 1, w: 2, h: 2 },
      { i: "avatar", x: 0, y: 2, w: 2, h: 2 },
      { i: "cardStack", x: 2, y: 2, w: 2, h: 2 },
      { i: "iconCloud", x: 3, y: 3, w: 1, h: 2 },
      { i: "miniModel", x: 0, y: 3, w: 1, h: 2 },
      { i: "themeSwitch", x: 1, y: 3, w: 1, h: 2 },
      { i: "mapComponent", x: 2, y: 3, w: 1, h: 2 },
    ],
    sm: [
      { i: "tinySwords", x: 0, y: 0, w: 2, h: 1 },
      { i: "speechEmotion", x: 0, y: 1, w: 2, h: 2 },
      { i: "goldPrice", x: 0, y: 3, w: 2, h: 1 },
      { i: "driverDrowsiness", x: 0, y: 4, w: 2, h: 1 },
      { i: "hemo", x: 0, y: 5, w: 2, h: 1 },
      { i: "cyberSleuth", x: 0, y: 6, w: 2, h: 1 },
      { i: "musicGenre", x: 0, y: 7, w: 2, h: 2 },

      { i: "avatar", x: 0, y: 13, w: 2, h: 2 },
      { i: "themeSwitch", x: 0, y: 11, w: 1, h: 1 },
      { i: "about", x: 1, y: 11, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 12, w: 1, h: 1 },
      { i: "cardStack", x: 0, y: 9, w: 2, h: 2 },


    ],
    xs: [
      { i: "tinySwords", x: 0, y: 0, w: 2, h: 1 },
      { i: "speechEmotion", x: 0, y: 1, w: 2, h: 2 },
      { i: "goldPrice", x: 0, y: 3, w: 2, h: 1 },
      { i: "driverDrowsiness", x: 0, y: 4, w: 2, h: 1 },
      { i: "hemo", x: 0, y: 5, w: 2, h: 1 },
      { i: "cyberSleuth", x: 0, y: 6, w: 2, h: 1 },
      { i: "musicGenre", x: 0, y: 7, w: 2, h: 2 },

      { i: "avatar", x: 0, y: 13, w: 2, h: 2 },
      { i: "themeSwitch", x: 0, y: 11, w: 1, h: 1 },
      { i: "about", x: 1, y: 11, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 12, w: 1, h: 1 },
      { i: "cardStack", x: 0, y: 9, w: 2, h: 2 },

    ],
    xxs: [
      { i: "tinySwords", x: 0, y: 0, w: 2, h: 1 },
      { i: "speechEmotion", x: 0, y: 1, w: 2, h: 2 },
      { i: "goldPrice", x: 0, y: 3, w: 2, h: 1 },
      { i: "driverDrowsiness", x: 0, y: 4, w: 2, h: 1 },
      { i: "hemo", x: 0, y: 5, w: 2, h: 1 },
      { i: "cyberSleuth", x: 0, y: 6, w: 2, h: 1 },
      { i: "musicGenre", x: 0, y: 7, w: 2, h: 2 },

      { i: "avatar", x: 0, y: 13, w: 2, h: 2 },
      { i: "themeSwitch", x: 0, y: 11, w: 1, h: 1 },
      { i: "about", x: 1, y: 11, w: 1, h: 2 },
      { i: "iconCloud", x: 0, y: 12, w: 1, h: 1 },
      { i: "cardStack", x: 0, y: 9, w: 2, h: 2 },

    ],
  },
};

export const selectedCard: Record<string, Record<string, boolean>> = {
  all: {
    avatar: true,
    themeSwitch: true,
    cardStack: true,
    iconCloud: true,
    speechEmotion: true,
    driverDrowsiness: true,
    goldPrice: true,
    tinySwords: true,
    musicGenre: true,
    hemo: true,
    cyberSleuth: true,
    about: true,
  },
  about: {
    avatar: true,
    themeSwitch: true,
    cardStack: true,
    iconCloud: true,
    speechEmotion: false,
    driverDrowsiness: false,
    goldPrice: false,
    tinySwords: false,
    musicGenre: false,
    hemo: false,
    cyberSleuth: false,
    about: true,
  },
  projects: {
    avatar: false,
    themeSwitch: false,
    cardStack: false,
    iconCloud: false,
    speechEmotion: true,
    driverDrowsiness: true,
    goldPrice: true,
    tinySwords: true,
    musicGenre: true,
    hemo: true,
    cyberSleuth: true,
    about: false,
  },
};
